# Generated by Django 3.1.13 on 2022-12-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libName', models.TextField(choices=[('main', '中正'), ('dh', '達賢'), ('zhongtu', '綜圖'), ('shangtu', '商圖')], default='')),
                ('libState', models.TextField(choices=[('crowded', '擁擠'), ('free', '空閒')], default='crowded')),
                ('libRes_crowded', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('libRes_free', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('libInfo', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'library',
            },
        ),
    ]
