# Generated by Django 3.1.13 on 2022-12-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='libRes_crowded',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='library',
            name='libRes_free',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
